# Generated by Django 5.1.3 on 2026-10-06 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('channel_phaseout', 'Channel Phase-out Alert'), ('discount_start', 'Discount Start'), ('discount_started', 'Discount Started'), ('discount_ended', 'Discount Ended'), ('discount_ending', 'Discount Ending Soon'), ('discount_available', 'Discount Available'), ('payment_success', 'Payment Success'), ('payment_failed', 'Payment Failed'), ('invoice_generated', 'Invoice Generated'), ('ad_flagged_by_admin', 'Ad Flagged by Admin'), ('ad_reported', 'Ad Reported by User'), ('listing_reported', 'Listing Reported by User'), ('grace_period_started', 'Grace Period Started'), ('grace_period_expired', 'Grace Period Expired'), ('account_suspended', 'Account Suspended'), ('business_approved', 'Business Account Approved'), ('business_approved_billing_reminder', 'Business Approved - Billing Reminder'), ('ad_phased_out', 'Advertisement Phased Out')], max_length=50),
        ),
    ]
