# Generated by Django 5.1.3 on 2026-10-07 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_notification_notification_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='personal_phone',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
