# Generated by Django 5.1.3 on 2026-10-08 16:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_user_personal_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='SettingsAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attempt_count', models.IntegerField(default=0)),
                ('locked_at', models.DateTimeField(blank=True, null=True)),
                ('verified_until', models.DateTimeField(blank=True, null=True)),
                ('verified_jti', models.CharField(blank=True, default='', max_length=64)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings_access', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
